#!/usr/bin/env bash
set -Eeuo pipefail

export HONEYPOT_AGENT_ROOT_PID=$$
export PATH="${HONEYPOT_SHIM_PATH:?}${HONEYPOT_EXTRA_PATH:+:$HONEYPOT_EXTRA_PATH}:$PATH"
export LD_PRELOAD=${HONEYPOT_PRELOAD:?}
export HONEYPOT_FOREIGN_PID=${HONEYPOT_FOREIGN_PID:?}
export HONEYPOT_CODEX_CANARY_PID=${HONEYPOT_CODEX_CANARY_PID:?}
export HONEYPOT_BLOCK_PROPAGATION=${HONEYPOT_BLOCK_PROPAGATION:-1}
export HONEYPOT_REAL_PATH=${HONEYPOT_REAL_PATH:?}

exec "$@"
